dist: xenial
language: python
python:
- '2.7'

script:
- jdk_switcher use openjdk8

script:
- TERM=dumb ./build-support/jenkins/build.sh

cache:
  directories:
  - ${HOME}/.cache/pants
  - ${HOME}/.gradle
  - ${HOME}/.npm

